// Mocks generated by Mockito 5.4.6 from annotations
// in social_app/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i20;

import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i19;
import 'package:social_app/app/internet_connection/connection_status.dart'
    as _i21;
import 'package:social_app/app/internet_connection/network_info.dart' as _i3;
import 'package:social_app/core/core.dart' as _i18;
import 'package:social_app/core/data/http/http_response.dart' as _i7;
import 'package:social_app/core/domain/usecases/usecases.dart' as _i29;
import 'package:social_app/features/auth/data/datasources/local/auth_local_data_source.dart'
    as _i4;
import 'package:social_app/features/auth/data/datasources/remote/auth_firebase_remote_data_souce.dart'
    as _i24;
import 'package:social_app/features/auth/data/datasources/remote/auth_remote_data_source.dart'
    as _i22;
import 'package:social_app/features/auth/data/models/auth_tokens_model.dart'
    as _i23;
import 'package:social_app/features/auth/domain/auth_params.dart' as _i26;
import 'package:social_app/features/auth/domain/entities/auth_tokens.dart'
    as _i6;
import 'package:social_app/features/auth/domain/repositories/auth_repository.dart'
    as _i9;
import 'package:social_app/features/auth/domain/usecases/check_auth_status_usecase.dart'
    as _i31;
import 'package:social_app/features/auth/domain/usecases/get_current_user_usecase.dart'
    as _i30;
import 'package:social_app/features/auth/domain/usecases/login_usecase.dart'
    as _i25;
import 'package:social_app/features/auth/domain/usecases/logout_usecase.dart'
    as _i28;
import 'package:social_app/features/auth/domain/usecases/register_usecase.dart'
    as _i27;
import 'package:social_app/features/comment/data/datasources/comment_remote_data_source.dart'
    as _i39;
import 'package:social_app/features/comment/data/models/comment_model.dart'
    as _i40;
import 'package:social_app/features/comment/domain/entities/comment_entity.dart'
    as _i11;
import 'package:social_app/features/comment/domain/repositories/comment_repository.dart'
    as _i37;
import 'package:social_app/features/comment/domain/value_objects/pagination_params.dart'
    as _i38;
import 'package:social_app/features/conversation/data/datasources/local/conversation_local_data_source.dart'
    as _i43;
import 'package:social_app/features/conversation/data/datasources/remote/conversation_remote_data_source.dart'
    as _i42;
import 'package:social_app/features/conversation/data/models/conversation_model.dart'
    as _i13;
import 'package:social_app/features/conversation/domain/conversation_params.dart'
    as _i47;
import 'package:social_app/features/conversation/domain/entites/conversation_entity.dart'
    as _i12;
import 'package:social_app/features/conversation/domain/repositories/conversation_repository.dart'
    as _i41;
import 'package:social_app/features/conversation/domain/usecases/create_conversation_usecase.dart'
    as _i46;
import 'package:social_app/features/conversation/domain/usecases/get_conversation_usecase.dart'
    as _i44;
import 'package:social_app/features/conversation/domain/usecases/get_conversations_usecase.dart'
    as _i45;
import 'package:social_app/features/conversation/domain/usecases/update_conversation_usecase.dart'
    as _i48;
import 'package:social_app/features/conversation/domain/usecases/watch_conversations_usecase.dart'
    as _i49;
import 'package:social_app/features/friendship/data/datasources/friendship_remote_data_source.dart'
    as _i54;
import 'package:social_app/features/friendship/data/models/friendship_model.dart'
    as _i17;
import 'package:social_app/features/friendship/domain/entities/friendship_entity.dart'
    as _i16;
import 'package:social_app/features/friendship/domain/repositories/friendship_repository.dart'
    as _i53;
import 'package:social_app/features/post/data/datasources/post_local_data_source.dart'
    as _i36;
import 'package:social_app/features/post/data/datasources/post_remote_data_source.dart'
    as _i34;
import 'package:social_app/features/post/data/models/post_model.dart' as _i35;
import 'package:social_app/features/post/domain/entities/post_entity.dart'
    as _i10;
import 'package:social_app/features/post/domain/entities/post_enum.dart'
    as _i33;
import 'package:social_app/features/post/domain/repositories/post_repository.dart'
    as _i32;
import 'package:social_app/features/reaction/data/datasources/reaction_remote_data_source.dart'
    as _i52;
import 'package:social_app/features/reaction/data/models/reaction_model.dart'
    as _i15;
import 'package:social_app/features/reaction/domain/entities/reaction_entity.dart'
    as _i14;
import 'package:social_app/features/reaction/domain/entities/reaction_enums.dart'
    as _i51;
import 'package:social_app/features/reaction/domain/repositories/reaction_repository.dart'
    as _i50;
import 'package:social_app/features/user/data/models/user_model.dart' as _i8;
import 'package:social_app/features/user/domain/entites/user_entity.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNetworkInfo_1 extends _i1.SmartFake implements _i3.NetworkInfo {
  _FakeNetworkInfo_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthLocalDataSource_2 extends _i1.SmartFake
    implements _i4.AuthLocalDataSource {
  _FakeAuthLocalDataSource_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserEntity_3 extends _i1.SmartFake implements _i5.UserEntity {
  _FakeUserEntity_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthTokens_4 extends _i1.SmartFake implements _i6.AuthTokens {
  _FakeAuthTokens_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpResponse_5<T> extends _i1.SmartFake
    implements _i7.HttpResponse<T> {
  _FakeHttpResponse_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserModel_6 extends _i1.SmartFake implements _i8.UserModel {
  _FakeUserModel_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthRepository_7 extends _i1.SmartFake
    implements _i9.AuthRepository {
  _FakeAuthRepository_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostEntity_8 extends _i1.SmartFake implements _i10.PostEntity {
  _FakePostEntity_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCommentEntity_9 extends _i1.SmartFake implements _i11.CommentEntity {
  _FakeCommentEntity_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConversationEntity_10 extends _i1.SmartFake
    implements _i12.ConversationEntity {
  _FakeConversationEntity_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConversationModel_11 extends _i1.SmartFake
    implements _i13.ConversationModel {
  _FakeConversationModel_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReactionResponseEntity_12 extends _i1.SmartFake
    implements _i14.ReactionResponseEntity {
  _FakeReactionResponseEntity_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReactionResponseModel_13 extends _i1.SmartFake
    implements _i15.ReactionResponseModel {
  _FakeReactionResponseModel_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFriendshipResponseEntity_14 extends _i1.SmartFake
    implements _i16.FriendshipResponseEntity {
  _FakeFriendshipResponseEntity_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFriendshipStatusEntity_15 extends _i1.SmartFake
    implements _i16.FriendshipStatusEntity {
  _FakeFriendshipStatusEntity_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFriendshipResponseModel_16 extends _i1.SmartFake
    implements _i17.FriendshipResponseModel {
  _FakeFriendshipResponseModel_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFriendshipStatusModel_17 extends _i1.SmartFake
    implements _i17.FriendshipStatusModel {
  _FakeFriendshipStatusModel_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i18.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get httpClient =>
      (super.noSuchMethod(
            Invocation.getter(#httpClient),
            returnValue: _FakeClient_0(this, Invocation.getter(#httpClient)),
          )
          as _i2.Client);

  @override
  _i3.NetworkInfo get networkInfo =>
      (super.noSuchMethod(
            Invocation.getter(#networkInfo),
            returnValue: _FakeNetworkInfo_1(
              this,
              Invocation.getter(#networkInfo),
            ),
          )
          as _i3.NetworkInfo);

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i4.AuthLocalDataSource get tokenProvider =>
      (super.noSuchMethod(
            Invocation.getter(#tokenProvider),
            returnValue: _FakeAuthLocalDataSource_2(
              this,
              Invocation.getter(#tokenProvider),
            ),
          )
          as _i4.AuthLocalDataSource);

  @override
  _i20.Future<Map<String, dynamic>> request({
    required String? method,
    required String? endpoint,
    Map<String, dynamic>? body,
    Map<String, String>? query,
    String? token,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#request, [], {
              #method: method,
              #endpoint: endpoint,
              #body: body,
              #query: query,
              #token: token,
              #headers: headers,
            }),
            returnValue: _i20.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i20.Future<Map<String, dynamic>>);

  @override
  _i20.Future<Map<String, dynamic>?> upload({
    required String? endpoint,
    required _i2.MultipartRequest? request,
    String? token,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upload, [], {
              #endpoint: endpoint,
              #request: request,
              #token: token,
              #headers: headers,
            }),
            returnValue: _i20.Future<Map<String, dynamic>?>.value(),
          )
          as _i20.Future<Map<String, dynamic>?>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i3.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i20.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i20.Future<bool>.value(false),
          )
          as _i20.Future<bool>);

  @override
  _i20.Future<_i21.ConnectionStatus> get connectionStatus =>
      (super.noSuchMethod(
            Invocation.getter(#connectionStatus),
            returnValue: _i20.Future<_i21.ConnectionStatus>.value(
              _i21.ConnectionStatus.unknown,
            ),
          )
          as _i20.Future<_i21.ConnectionStatus>);

  @override
  _i20.Stream<_i21.ConnectionStatus> get onStatusChange =>
      (super.noSuchMethod(
            Invocation.getter(#onStatusChange),
            returnValue: _i20.Stream<_i21.ConnectionStatus>.empty(),
          )
          as _i20.Stream<_i21.ConnectionStatus>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i9.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i20.Future<_i5.UserEntity> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue: _i20.Future<_i5.UserEntity>.value(
              _FakeUserEntity_3(
                this,
                Invocation.method(#login, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i20.Future<_i5.UserEntity>);

  @override
  _i20.Future<_i5.UserEntity> register({
    required String? email,
    required String? username,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #email: email,
              #username: username,
              #password: password,
            }),
            returnValue: _i20.Future<_i5.UserEntity>.value(
              _FakeUserEntity_3(
                this,
                Invocation.method(#register, [], {
                  #email: email,
                  #username: username,
                  #password: password,
                }),
              ),
            ),
          )
          as _i20.Future<_i5.UserEntity>);

  @override
  _i20.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<_i5.UserEntity> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i20.Future<_i5.UserEntity>.value(
              _FakeUserEntity_3(this, Invocation.method(#getCurrentUser, [])),
            ),
          )
          as _i20.Future<_i5.UserEntity>);

  @override
  _i20.Future<bool> isAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticated, []),
            returnValue: _i20.Future<bool>.value(false),
          )
          as _i20.Future<bool>);

  @override
  _i20.Future<_i6.AuthTokens?> getAuthTokens() =>
      (super.noSuchMethod(
            Invocation.method(#getAuthTokens, []),
            returnValue: _i20.Future<_i6.AuthTokens?>.value(),
          )
          as _i20.Future<_i6.AuthTokens?>);

  @override
  _i20.Future<_i6.AuthTokens> refreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, []),
            returnValue: _i20.Future<_i6.AuthTokens>.value(
              _FakeAuthTokens_4(this, Invocation.method(#refreshToken, [])),
            ),
          )
          as _i20.Future<_i6.AuthTokens>);

  @override
  _i20.Future<_i5.UserEntity> updateProfile({
    String? displayName,
    String? bio,
    String? avatarUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #displayName: displayName,
              #bio: bio,
              #avatarUrl: avatarUrl,
            }),
            returnValue: _i20.Future<_i5.UserEntity>.value(
              _FakeUserEntity_3(
                this,
                Invocation.method(#updateProfile, [], {
                  #displayName: displayName,
                  #bio: bio,
                  #avatarUrl: avatarUrl,
                }),
              ),
            ),
          )
          as _i20.Future<_i5.UserEntity>);

  @override
  _i20.Future<void> changePassword({
    required String? currentPassword,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [], {
              #currentPassword: currentPassword,
              #newPassword: newPassword,
            }),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<void> requestPasswordReset({required String? email}) =>
      (super.noSuchMethod(
            Invocation.method(#requestPasswordReset, [], {#email: email}),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<void> resetPassword({
    required String? token,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {
              #token: token,
              #newPassword: newPassword,
            }),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<void> verifyEmail({required String? token}) =>
      (super.noSuchMethod(
            Invocation.method(#verifyEmail, [], {#token: token}),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i22.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i20.Future<_i7.HttpResponse<Map<String, dynamic>>> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue:
                _i20.Future<_i7.HttpResponse<Map<String, dynamic>>>.value(
                  _FakeHttpResponse_5<Map<String, dynamic>>(
                    this,
                    Invocation.method(#login, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i20.Future<_i7.HttpResponse<Map<String, dynamic>>>);

  @override
  _i20.Future<_i7.HttpResponse<Map<String, dynamic>>> register({
    required String? email,
    required String? username,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #email: email,
              #username: username,
              #password: password,
            }),
            returnValue:
                _i20.Future<_i7.HttpResponse<Map<String, dynamic>>>.value(
                  _FakeHttpResponse_5<Map<String, dynamic>>(
                    this,
                    Invocation.method(#register, [], {
                      #email: email,
                      #username: username,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i20.Future<_i7.HttpResponse<Map<String, dynamic>>>);

  @override
  _i20.Future<_i7.HttpResponse<void>> logout(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [userId]),
            returnValue: _i20.Future<_i7.HttpResponse<void>>.value(
              _FakeHttpResponse_5<void>(
                this,
                Invocation.method(#logout, [userId]),
              ),
            ),
          )
          as _i20.Future<_i7.HttpResponse<void>>);

  @override
  _i20.Future<_i7.HttpResponse<_i8.UserModel>> getCurrentUser({
    required String? accessToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, [], {#accessToken: accessToken}),
            returnValue: _i20.Future<_i7.HttpResponse<_i8.UserModel>>.value(
              _FakeHttpResponse_5<_i8.UserModel>(
                this,
                Invocation.method(#getCurrentUser, [], {
                  #accessToken: accessToken,
                }),
              ),
            ),
          )
          as _i20.Future<_i7.HttpResponse<_i8.UserModel>>);

  @override
  _i20.Future<_i7.HttpResponse<_i8.UserModel>> updateProfile({
    required String? accessToken,
    String? displayName,
    String? bio,
    String? avatarUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #accessToken: accessToken,
              #displayName: displayName,
              #bio: bio,
              #avatarUrl: avatarUrl,
            }),
            returnValue: _i20.Future<_i7.HttpResponse<_i8.UserModel>>.value(
              _FakeHttpResponse_5<_i8.UserModel>(
                this,
                Invocation.method(#updateProfile, [], {
                  #accessToken: accessToken,
                  #displayName: displayName,
                  #bio: bio,
                  #avatarUrl: avatarUrl,
                }),
              ),
            ),
          )
          as _i20.Future<_i7.HttpResponse<_i8.UserModel>>);

  @override
  _i20.Future<_i7.HttpResponse<void>> changePassword({
    required String? accessToken,
    required String? currentPassword,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [], {
              #accessToken: accessToken,
              #currentPassword: currentPassword,
              #newPassword: newPassword,
            }),
            returnValue: _i20.Future<_i7.HttpResponse<void>>.value(
              _FakeHttpResponse_5<void>(
                this,
                Invocation.method(#changePassword, [], {
                  #accessToken: accessToken,
                  #currentPassword: currentPassword,
                  #newPassword: newPassword,
                }),
              ),
            ),
          )
          as _i20.Future<_i7.HttpResponse<void>>);

  @override
  _i20.Future<_i7.HttpResponse<void>> requestPasswordReset({
    required String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#requestPasswordReset, [], {#email: email}),
            returnValue: _i20.Future<_i7.HttpResponse<void>>.value(
              _FakeHttpResponse_5<void>(
                this,
                Invocation.method(#requestPasswordReset, [], {#email: email}),
              ),
            ),
          )
          as _i20.Future<_i7.HttpResponse<void>>);

  @override
  _i20.Future<_i7.HttpResponse<void>> resetPassword({
    required String? token,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {
              #token: token,
              #newPassword: newPassword,
            }),
            returnValue: _i20.Future<_i7.HttpResponse<void>>.value(
              _FakeHttpResponse_5<void>(
                this,
                Invocation.method(#resetPassword, [], {
                  #token: token,
                  #newPassword: newPassword,
                }),
              ),
            ),
          )
          as _i20.Future<_i7.HttpResponse<void>>);

  @override
  _i20.Future<_i7.HttpResponse<void>> verifyEmail({required String? token}) =>
      (super.noSuchMethod(
            Invocation.method(#verifyEmail, [], {#token: token}),
            returnValue: _i20.Future<_i7.HttpResponse<void>>.value(
              _FakeHttpResponse_5<void>(
                this,
                Invocation.method(#verifyEmail, [], {#token: token}),
              ),
            ),
          )
          as _i20.Future<_i7.HttpResponse<void>>);

  @override
  _i20.Future<_i7.HttpResponse<Map<String, dynamic>>> refreshToken({
    required String? refreshToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, [], {#refreshToken: refreshToken}),
            returnValue:
                _i20.Future<_i7.HttpResponse<Map<String, dynamic>>>.value(
                  _FakeHttpResponse_5<Map<String, dynamic>>(
                    this,
                    Invocation.method(#refreshToken, [], {
                      #refreshToken: refreshToken,
                    }),
                  ),
                ),
          )
          as _i20.Future<_i7.HttpResponse<Map<String, dynamic>>>);
}

/// A class which mocks [AuthLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDataSource extends _i1.Mock
    implements _i4.AuthLocalDataSource {
  MockAuthLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i20.Future<void> cacheUser(_i8.UserModel? user) =>
      (super.noSuchMethod(
            Invocation.method(#cacheUser, [user]),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<_i8.UserModel?> getCachedUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedUser, []),
            returnValue: _i20.Future<_i8.UserModel?>.value(),
          )
          as _i20.Future<_i8.UserModel?>);

  @override
  _i20.Future<void> clearCachedUser() =>
      (super.noSuchMethod(
            Invocation.method(#clearCachedUser, []),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<void> cacheTokens(_i23.AuthTokensModel? tokens) =>
      (super.noSuchMethod(
            Invocation.method(#cacheTokens, [tokens]),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<_i23.AuthTokensModel?> getCachedTokens() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedTokens, []),
            returnValue: _i20.Future<_i23.AuthTokensModel?>.value(),
          )
          as _i20.Future<_i23.AuthTokensModel?>);

  @override
  _i20.Future<void> clearCachedTokens() =>
      (super.noSuchMethod(
            Invocation.method(#clearCachedTokens, []),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<void> clearAllData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllData, []),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);
}

/// A class which mocks [AuthFirebaseRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthFirebaseRemoteDataSource extends _i1.Mock
    implements _i24.AuthFirebaseRemoteDataSource {
  MockAuthFirebaseRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i20.Future<Map<String, dynamic>> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue: _i20.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i20.Future<Map<String, dynamic>>);

  @override
  _i20.Future<Map<String, dynamic>> register({
    required String? email,
    required String? username,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #email: email,
              #username: username,
              #password: password,
            }),
            returnValue: _i20.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i20.Future<Map<String, dynamic>>);

  @override
  _i20.Future<void> logout(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [userId]),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<_i8.UserModel> getCurrentUser({required String? accessToken}) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, [], {#accessToken: accessToken}),
            returnValue: _i20.Future<_i8.UserModel>.value(
              _FakeUserModel_6(
                this,
                Invocation.method(#getCurrentUser, [], {
                  #accessToken: accessToken,
                }),
              ),
            ),
          )
          as _i20.Future<_i8.UserModel>);

  @override
  _i20.Future<_i8.UserModel> updateProfile({
    required String? accessToken,
    String? displayName,
    String? bio,
    String? avatarUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #accessToken: accessToken,
              #displayName: displayName,
              #bio: bio,
              #avatarUrl: avatarUrl,
            }),
            returnValue: _i20.Future<_i8.UserModel>.value(
              _FakeUserModel_6(
                this,
                Invocation.method(#updateProfile, [], {
                  #accessToken: accessToken,
                  #displayName: displayName,
                  #bio: bio,
                  #avatarUrl: avatarUrl,
                }),
              ),
            ),
          )
          as _i20.Future<_i8.UserModel>);

  @override
  _i20.Future<void> changePassword({
    required String? accessToken,
    required String? currentPassword,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [], {
              #accessToken: accessToken,
              #currentPassword: currentPassword,
              #newPassword: newPassword,
            }),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<void> requestPasswordReset({required String? email}) =>
      (super.noSuchMethod(
            Invocation.method(#requestPasswordReset, [], {#email: email}),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<void> resetPassword({
    required String? token,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {
              #token: token,
              #newPassword: newPassword,
            }),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<void> verifyEmail({required String? token}) =>
      (super.noSuchMethod(
            Invocation.method(#verifyEmail, [], {#token: token}),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<Map<String, dynamic>> refreshToken({
    required String? refreshToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, [], {#refreshToken: refreshToken}),
            returnValue: _i20.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i20.Future<Map<String, dynamic>>);
}

/// A class which mocks [LoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUseCase extends _i1.Mock implements _i25.LoginUseCase {
  MockLoginUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_7(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i9.AuthRepository);

  @override
  _i20.Future<_i5.UserEntity> call(_i26.LoginParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i20.Future<_i5.UserEntity>.value(
              _FakeUserEntity_3(this, Invocation.method(#call, [params])),
            ),
          )
          as _i20.Future<_i5.UserEntity>);
}

/// A class which mocks [RegisterUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterUseCase extends _i1.Mock implements _i27.RegisterUseCase {
  MockRegisterUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_7(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i9.AuthRepository);

  @override
  _i20.Future<_i5.UserEntity> call(_i26.RegisterParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i20.Future<_i5.UserEntity>.value(
              _FakeUserEntity_3(this, Invocation.method(#call, [params])),
            ),
          )
          as _i20.Future<_i5.UserEntity>);
}

/// A class which mocks [LogoutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogoutUseCase extends _i1.Mock implements _i28.LogoutUseCase {
  MockLogoutUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_7(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i9.AuthRepository);

  @override
  _i20.Future<void> call(_i29.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);
}

/// A class which mocks [GetCurrentUserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCurrentUserUseCase extends _i1.Mock
    implements _i30.GetCurrentUserUseCase {
  MockGetCurrentUserUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_7(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i9.AuthRepository);

  @override
  _i20.Future<_i5.UserEntity> call(_i29.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i20.Future<_i5.UserEntity>.value(
              _FakeUserEntity_3(this, Invocation.method(#call, [params])),
            ),
          )
          as _i20.Future<_i5.UserEntity>);
}

/// A class which mocks [CheckAuthStatusUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckAuthStatusUseCase extends _i1.Mock
    implements _i31.CheckAuthStatusUseCase {
  MockCheckAuthStatusUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_7(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i9.AuthRepository);

  @override
  _i20.Future<bool> call(_i29.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i20.Future<bool>.value(false),
          )
          as _i20.Future<bool>);
}

/// A class which mocks [PostRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostRepository extends _i1.Mock implements _i32.PostRepository {
  MockPostRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i20.Future<_i10.PostEntity> createPost({
    required String? content,
    required _i33.PostVisibility? visibility,
    required _i33.PostType? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPost, [], {
              #content: content,
              #visibility: visibility,
              #type: type,
            }),
            returnValue: _i20.Future<_i10.PostEntity>.value(
              _FakePostEntity_8(
                this,
                Invocation.method(#createPost, [], {
                  #content: content,
                  #visibility: visibility,
                  #type: type,
                }),
              ),
            ),
          )
          as _i20.Future<_i10.PostEntity>);

  @override
  _i20.Future<_i10.PostEntity> updatePost({
    required String? postId,
    required String? content,
    required _i33.PostVisibility? visibility,
    required _i33.PostType? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePost, [], {
              #postId: postId,
              #content: content,
              #visibility: visibility,
              #type: type,
            }),
            returnValue: _i20.Future<_i10.PostEntity>.value(
              _FakePostEntity_8(
                this,
                Invocation.method(#updatePost, [], {
                  #postId: postId,
                  #content: content,
                  #visibility: visibility,
                  #type: type,
                }),
              ),
            ),
          )
          as _i20.Future<_i10.PostEntity>);

  @override
  _i20.Future<void> deletePost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePost, [postId]),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<_i10.PostEntity> getPost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#getPost, [postId]),
            returnValue: _i20.Future<_i10.PostEntity>.value(
              _FakePostEntity_8(this, Invocation.method(#getPost, [postId])),
            ),
          )
          as _i20.Future<_i10.PostEntity>);

  @override
  _i20.Future<List<_i10.PostEntity>> getHomePost() =>
      (super.noSuchMethod(
            Invocation.method(#getHomePost, []),
            returnValue: _i20.Future<List<_i10.PostEntity>>.value(
              <_i10.PostEntity>[],
            ),
          )
          as _i20.Future<List<_i10.PostEntity>>);

  @override
  _i20.Future<List<_i10.PostEntity>> getPostsByUser(String? viewerId) =>
      (super.noSuchMethod(
            Invocation.method(#getPostsByUser, [viewerId]),
            returnValue: _i20.Future<List<_i10.PostEntity>>.value(
              <_i10.PostEntity>[],
            ),
          )
          as _i20.Future<List<_i10.PostEntity>>);
}

/// A class which mocks [PostRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostRemoteDataSource extends _i1.Mock
    implements _i34.PostRemoteDataSource {
  MockPostRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i20.Future<_i7.HttpResponse<_i35.PostModel>> createPost({
    required String? content,
    required String? visibility,
    required String? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPost, [], {
              #content: content,
              #visibility: visibility,
              #type: type,
            }),
            returnValue: _i20.Future<_i7.HttpResponse<_i35.PostModel>>.value(
              _FakeHttpResponse_5<_i35.PostModel>(
                this,
                Invocation.method(#createPost, [], {
                  #content: content,
                  #visibility: visibility,
                  #type: type,
                }),
              ),
            ),
          )
          as _i20.Future<_i7.HttpResponse<_i35.PostModel>>);

  @override
  _i20.Future<_i7.HttpResponse<_i35.PostModel>> updatePost({
    required String? postId,
    required String? content,
    required String? visibility,
    required String? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePost, [], {
              #postId: postId,
              #content: content,
              #visibility: visibility,
              #type: type,
            }),
            returnValue: _i20.Future<_i7.HttpResponse<_i35.PostModel>>.value(
              _FakeHttpResponse_5<_i35.PostModel>(
                this,
                Invocation.method(#updatePost, [], {
                  #postId: postId,
                  #content: content,
                  #visibility: visibility,
                  #type: type,
                }),
              ),
            ),
          )
          as _i20.Future<_i7.HttpResponse<_i35.PostModel>>);

  @override
  _i20.Future<_i7.HttpResponse<void>> deletePost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePost, [postId]),
            returnValue: _i20.Future<_i7.HttpResponse<void>>.value(
              _FakeHttpResponse_5<void>(
                this,
                Invocation.method(#deletePost, [postId]),
              ),
            ),
          )
          as _i20.Future<_i7.HttpResponse<void>>);

  @override
  _i20.Future<_i7.HttpResponse<_i35.PostModel>> getPost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#getPost, [postId]),
            returnValue: _i20.Future<_i7.HttpResponse<_i35.PostModel>>.value(
              _FakeHttpResponse_5<_i35.PostModel>(
                this,
                Invocation.method(#getPost, [postId]),
              ),
            ),
          )
          as _i20.Future<_i7.HttpResponse<_i35.PostModel>>);

  @override
  _i20.Future<_i7.HttpResponse<List<_i35.PostModel>>> getHomePost() =>
      (super.noSuchMethod(
            Invocation.method(#getHomePost, []),
            returnValue:
                _i20.Future<_i7.HttpResponse<List<_i35.PostModel>>>.value(
                  _FakeHttpResponse_5<List<_i35.PostModel>>(
                    this,
                    Invocation.method(#getHomePost, []),
                  ),
                ),
          )
          as _i20.Future<_i7.HttpResponse<List<_i35.PostModel>>>);

  @override
  _i20.Future<_i7.HttpResponse<List<_i35.PostModel>>> getPostsByUser(
    String? viewerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPostsByUser, [viewerId]),
            returnValue:
                _i20.Future<_i7.HttpResponse<List<_i35.PostModel>>>.value(
                  _FakeHttpResponse_5<List<_i35.PostModel>>(
                    this,
                    Invocation.method(#getPostsByUser, [viewerId]),
                  ),
                ),
          )
          as _i20.Future<_i7.HttpResponse<List<_i35.PostModel>>>);
}

/// A class which mocks [PostLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostLocalDataSource extends _i1.Mock
    implements _i36.PostLocalDataSource {
  MockPostLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i20.Future<void> cachePosts(List<_i35.PostModel>? posts) =>
      (super.noSuchMethod(
            Invocation.method(#cachePosts, [posts]),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<List<_i35.PostModel>?> getCachedPosts() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedPosts, []),
            returnValue: _i20.Future<List<_i35.PostModel>?>.value(),
          )
          as _i20.Future<List<_i35.PostModel>?>);

  @override
  _i20.Future<void> clearCachedPosts() =>
      (super.noSuchMethod(
            Invocation.method(#clearCachedPosts, []),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);
}

/// A class which mocks [CommentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommentRepository extends _i1.Mock implements _i37.CommentRepository {
  MockCommentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i20.Future<_i11.CommentEntity> createComment({
    required String? postId,
    required String? content,
    String? parentCommentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createComment, [], {
              #postId: postId,
              #content: content,
              #parentCommentId: parentCommentId,
            }),
            returnValue: _i20.Future<_i11.CommentEntity>.value(
              _FakeCommentEntity_9(
                this,
                Invocation.method(#createComment, [], {
                  #postId: postId,
                  #content: content,
                  #parentCommentId: parentCommentId,
                }),
              ),
            ),
          )
          as _i20.Future<_i11.CommentEntity>);

  @override
  _i20.Future<_i11.CommentEntity> updateComment({
    required String? commentId,
    required String? content,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateComment, [], {
              #commentId: commentId,
              #content: content,
            }),
            returnValue: _i20.Future<_i11.CommentEntity>.value(
              _FakeCommentEntity_9(
                this,
                Invocation.method(#updateComment, [], {
                  #commentId: commentId,
                  #content: content,
                }),
              ),
            ),
          )
          as _i20.Future<_i11.CommentEntity>);

  @override
  _i20.Future<void> deleteComment(String? commentId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteComment, [commentId]),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<List<_i11.CommentEntity>> getCommentsByPost({
    required String? postId,
    required _i38.PaginationParams? query,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCommentsByPost, [], {
              #postId: postId,
              #query: query,
            }),
            returnValue: _i20.Future<List<_i11.CommentEntity>>.value(
              <_i11.CommentEntity>[],
            ),
          )
          as _i20.Future<List<_i11.CommentEntity>>);

  @override
  _i20.Future<List<_i11.CommentEntity>> getReplies({
    required String? commentId,
    required _i38.PaginationParams? query,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getReplies, [], {
              #commentId: commentId,
              #query: query,
            }),
            returnValue: _i20.Future<List<_i11.CommentEntity>>.value(
              <_i11.CommentEntity>[],
            ),
          )
          as _i20.Future<List<_i11.CommentEntity>>);
}

/// A class which mocks [CommentRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommentRemoteDataSource extends _i1.Mock
    implements _i39.CommentRemoteDataSource {
  MockCommentRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i20.Future<_i7.HttpResponse<_i40.CommentModel>> createComment({
    required String? postId,
    required String? content,
    String? parentCommentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createComment, [], {
              #postId: postId,
              #content: content,
              #parentCommentId: parentCommentId,
            }),
            returnValue: _i20.Future<_i7.HttpResponse<_i40.CommentModel>>.value(
              _FakeHttpResponse_5<_i40.CommentModel>(
                this,
                Invocation.method(#createComment, [], {
                  #postId: postId,
                  #content: content,
                  #parentCommentId: parentCommentId,
                }),
              ),
            ),
          )
          as _i20.Future<_i7.HttpResponse<_i40.CommentModel>>);

  @override
  _i20.Future<_i7.HttpResponse<_i40.CommentModel>> updateComment({
    required String? commentId,
    required String? content,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateComment, [], {
              #commentId: commentId,
              #content: content,
            }),
            returnValue: _i20.Future<_i7.HttpResponse<_i40.CommentModel>>.value(
              _FakeHttpResponse_5<_i40.CommentModel>(
                this,
                Invocation.method(#updateComment, [], {
                  #commentId: commentId,
                  #content: content,
                }),
              ),
            ),
          )
          as _i20.Future<_i7.HttpResponse<_i40.CommentModel>>);

  @override
  _i20.Future<_i7.HttpResponse<void>> deleteComment(String? commentId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteComment, [commentId]),
            returnValue: _i20.Future<_i7.HttpResponse<void>>.value(
              _FakeHttpResponse_5<void>(
                this,
                Invocation.method(#deleteComment, [commentId]),
              ),
            ),
          )
          as _i20.Future<_i7.HttpResponse<void>>);

  @override
  _i20.Future<_i7.HttpResponse<List<_i40.CommentModel>>> getCommentByPost({
    required String? postId,
    _i38.PaginationParams? pagination,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCommentByPost, [], {
              #postId: postId,
              #pagination: pagination,
            }),
            returnValue:
                _i20.Future<_i7.HttpResponse<List<_i40.CommentModel>>>.value(
                  _FakeHttpResponse_5<List<_i40.CommentModel>>(
                    this,
                    Invocation.method(#getCommentByPost, [], {
                      #postId: postId,
                      #pagination: pagination,
                    }),
                  ),
                ),
          )
          as _i20.Future<_i7.HttpResponse<List<_i40.CommentModel>>>);

  @override
  _i20.Future<_i7.HttpResponse<List<_i40.CommentModel>>> getReplies({
    required String? commentId,
    _i38.PaginationParams? pagination,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getReplies, [], {
              #commentId: commentId,
              #pagination: pagination,
            }),
            returnValue:
                _i20.Future<_i7.HttpResponse<List<_i40.CommentModel>>>.value(
                  _FakeHttpResponse_5<List<_i40.CommentModel>>(
                    this,
                    Invocation.method(#getReplies, [], {
                      #commentId: commentId,
                      #pagination: pagination,
                    }),
                  ),
                ),
          )
          as _i20.Future<_i7.HttpResponse<List<_i40.CommentModel>>>);
}

/// A class which mocks [ConversationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockConversationRepository extends _i1.Mock
    implements _i41.ConversationRepository {
  MockConversationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i20.Future<_i12.ConversationEntity> createConversation(
    List<String>? participantIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createConversation, [participantIds]),
            returnValue: _i20.Future<_i12.ConversationEntity>.value(
              _FakeConversationEntity_10(
                this,
                Invocation.method(#createConversation, [participantIds]),
              ),
            ),
          )
          as _i20.Future<_i12.ConversationEntity>);

  @override
  _i20.Future<_i12.ConversationEntity?> getConversation(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getConversation, [id]),
            returnValue: _i20.Future<_i12.ConversationEntity?>.value(),
          )
          as _i20.Future<_i12.ConversationEntity?>);

  @override
  _i20.Future<List<_i12.ConversationEntity>> getConversations(
    String? currentUserId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getConversations, [currentUserId]),
            returnValue: _i20.Future<List<_i12.ConversationEntity>>.value(
              <_i12.ConversationEntity>[],
            ),
          )
          as _i20.Future<List<_i12.ConversationEntity>>);

  @override
  _i20.Future<_i12.ConversationEntity> updateConversation(
    _i12.ConversationEntity? conversation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateConversation, [conversation]),
            returnValue: _i20.Future<_i12.ConversationEntity>.value(
              _FakeConversationEntity_10(
                this,
                Invocation.method(#updateConversation, [conversation]),
              ),
            ),
          )
          as _i20.Future<_i12.ConversationEntity>);

  @override
  _i20.Stream<List<_i12.ConversationEntity>> watchConversations(
    String? currentUserId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchConversations, [currentUserId]),
            returnValue: _i20.Stream<List<_i12.ConversationEntity>>.empty(),
          )
          as _i20.Stream<List<_i12.ConversationEntity>>);
}

/// A class which mocks [ConversationRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockConversationRemoteDataSource extends _i1.Mock
    implements _i42.ConversationRemoteDataSource {
  MockConversationRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i20.Future<_i13.ConversationModel> createConversation(
    List<String>? participantIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createConversation, [participantIds]),
            returnValue: _i20.Future<_i13.ConversationModel>.value(
              _FakeConversationModel_11(
                this,
                Invocation.method(#createConversation, [participantIds]),
              ),
            ),
          )
          as _i20.Future<_i13.ConversationModel>);

  @override
  _i20.Future<_i13.ConversationModel?> getConversation(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getConversation, [id]),
            returnValue: _i20.Future<_i13.ConversationModel?>.value(),
          )
          as _i20.Future<_i13.ConversationModel?>);

  @override
  _i20.Future<List<_i13.ConversationModel>> getConversations(
    String? currentUserId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getConversations, [currentUserId]),
            returnValue: _i20.Future<List<_i13.ConversationModel>>.value(
              <_i13.ConversationModel>[],
            ),
          )
          as _i20.Future<List<_i13.ConversationModel>>);

  @override
  _i20.Future<_i13.ConversationModel> updateConversation(
    _i12.ConversationEntity? conversation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateConversation, [conversation]),
            returnValue: _i20.Future<_i13.ConversationModel>.value(
              _FakeConversationModel_11(
                this,
                Invocation.method(#updateConversation, [conversation]),
              ),
            ),
          )
          as _i20.Future<_i13.ConversationModel>);

  @override
  _i20.Stream<List<_i13.ConversationModel>> watchConversations(
    String? currentUserId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchConversations, [currentUserId]),
            returnValue: _i20.Stream<List<_i13.ConversationModel>>.empty(),
          )
          as _i20.Stream<List<_i13.ConversationModel>>);
}

/// A class which mocks [ConversationLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockConversationLocalDataSource extends _i1.Mock
    implements _i43.ConversationLocalDataSource {
  MockConversationLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i20.Future<void> cacheConversations(
    String? userId,
    List<_i13.ConversationModel>? conversations,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cacheConversations, [userId, conversations]),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<List<_i13.ConversationModel>> getCachedConversations(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedConversations, [userId]),
            returnValue: _i20.Future<List<_i13.ConversationModel>>.value(
              <_i13.ConversationModel>[],
            ),
          )
          as _i20.Future<List<_i13.ConversationModel>>);

  @override
  _i20.Future<void> clearConversations(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#clearConversations, [userId]),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);
}

/// A class which mocks [GetConversationUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetConversationUsecase extends _i1.Mock
    implements _i44.GetConversationUsecase {
  MockGetConversationUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i20.Future<_i12.ConversationEntity?> call(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue: _i20.Future<_i12.ConversationEntity?>.value(),
          )
          as _i20.Future<_i12.ConversationEntity?>);
}

/// A class which mocks [GetConversationsUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetConversationsUsecase extends _i1.Mock
    implements _i45.GetConversationsUsecase {
  MockGetConversationsUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i20.Future<List<_i12.ConversationEntity>> call(String? currentUserId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [currentUserId]),
            returnValue: _i20.Future<List<_i12.ConversationEntity>>.value(
              <_i12.ConversationEntity>[],
            ),
          )
          as _i20.Future<List<_i12.ConversationEntity>>);
}

/// A class which mocks [CreateConversationUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateConversationUsecase extends _i1.Mock
    implements _i46.CreateConversationUsecase {
  MockCreateConversationUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i20.Future<_i12.ConversationEntity> call(
    _i47.CreateConversationParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i20.Future<_i12.ConversationEntity>.value(
              _FakeConversationEntity_10(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i20.Future<_i12.ConversationEntity>);
}

/// A class which mocks [UpdateConversationsUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateConversationsUsecase extends _i1.Mock
    implements _i48.UpdateConversationsUsecase {
  MockUpdateConversationsUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i20.Future<_i12.ConversationEntity> call(
    _i12.ConversationEntity? conversaion,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [conversaion]),
            returnValue: _i20.Future<_i12.ConversationEntity>.value(
              _FakeConversationEntity_10(
                this,
                Invocation.method(#call, [conversaion]),
              ),
            ),
          )
          as _i20.Future<_i12.ConversationEntity>);
}

/// A class which mocks [WatchConversationsUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchConversationsUsecase extends _i1.Mock
    implements _i49.WatchConversationsUsecase {
  MockWatchConversationsUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i20.Stream<List<_i12.ConversationEntity>> call(String? currentUserId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [currentUserId]),
            returnValue: _i20.Stream<List<_i12.ConversationEntity>>.empty(),
          )
          as _i20.Stream<List<_i12.ConversationEntity>>);
}

/// A class which mocks [ReactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockReactionRepository extends _i1.Mock
    implements _i50.ReactionRepository {
  MockReactionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i20.Future<_i14.ReactionResponseEntity> react({
    required _i51.ReactionTargetType? targetType,
    required String? targetId,
    required _i51.ReactionType? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#react, [], {
              #targetType: targetType,
              #targetId: targetId,
              #type: type,
            }),
            returnValue: _i20.Future<_i14.ReactionResponseEntity>.value(
              _FakeReactionResponseEntity_12(
                this,
                Invocation.method(#react, [], {
                  #targetType: targetType,
                  #targetId: targetId,
                  #type: type,
                }),
              ),
            ),
          )
          as _i20.Future<_i14.ReactionResponseEntity>);

  @override
  _i20.Future<List<_i14.ReactionSummaryEntity>> getReactionSummary({
    required _i51.ReactionTargetType? targetType,
    required String? targetId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getReactionSummary, [], {
              #targetType: targetType,
              #targetId: targetId,
            }),
            returnValue: _i20.Future<List<_i14.ReactionSummaryEntity>>.value(
              <_i14.ReactionSummaryEntity>[],
            ),
          )
          as _i20.Future<List<_i14.ReactionSummaryEntity>>);

  @override
  _i20.Future<_i14.ReactionEntity?> getUserReaction({
    required _i51.ReactionTargetType? targetType,
    required String? targetId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUserReaction, [], {
              #targetType: targetType,
              #targetId: targetId,
            }),
            returnValue: _i20.Future<_i14.ReactionEntity?>.value(),
          )
          as _i20.Future<_i14.ReactionEntity?>);
}

/// A class which mocks [ReactionRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockReactionRemoteDataSource extends _i1.Mock
    implements _i52.ReactionRemoteDataSource {
  MockReactionRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i20.Future<_i15.ReactionResponseModel> react({
    required _i51.ReactionTargetType? targetType,
    required String? targetId,
    required _i51.ReactionType? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#react, [], {
              #targetType: targetType,
              #targetId: targetId,
              #type: type,
            }),
            returnValue: _i20.Future<_i15.ReactionResponseModel>.value(
              _FakeReactionResponseModel_13(
                this,
                Invocation.method(#react, [], {
                  #targetType: targetType,
                  #targetId: targetId,
                  #type: type,
                }),
              ),
            ),
          )
          as _i20.Future<_i15.ReactionResponseModel>);

  @override
  _i20.Future<List<_i15.ReactionSummaryModel>> getReactionSummary({
    required _i51.ReactionTargetType? targetType,
    required String? targetId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getReactionSummary, [], {
              #targetType: targetType,
              #targetId: targetId,
            }),
            returnValue: _i20.Future<List<_i15.ReactionSummaryModel>>.value(
              <_i15.ReactionSummaryModel>[],
            ),
          )
          as _i20.Future<List<_i15.ReactionSummaryModel>>);

  @override
  _i20.Future<_i15.ReactionModel?> getUserReaction({
    required _i51.ReactionTargetType? targetType,
    required String? targetId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUserReaction, [], {
              #targetType: targetType,
              #targetId: targetId,
            }),
            returnValue: _i20.Future<_i15.ReactionModel?>.value(),
          )
          as _i20.Future<_i15.ReactionModel?>);
}

/// A class which mocks [FriendshipRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFriendshipRepository extends _i1.Mock
    implements _i53.FriendshipRepository {
  MockFriendshipRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i20.Future<_i16.FriendshipResponseEntity> sendRequest({
    required String? toUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendRequest, [], {#toUserId: toUserId}),
            returnValue: _i20.Future<_i16.FriendshipResponseEntity>.value(
              _FakeFriendshipResponseEntity_14(
                this,
                Invocation.method(#sendRequest, [], {#toUserId: toUserId}),
              ),
            ),
          )
          as _i20.Future<_i16.FriendshipResponseEntity>);

  @override
  _i20.Future<_i16.FriendshipResponseEntity> acceptRequest({
    required String? requestId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#acceptRequest, [], {#requestId: requestId}),
            returnValue: _i20.Future<_i16.FriendshipResponseEntity>.value(
              _FakeFriendshipResponseEntity_14(
                this,
                Invocation.method(#acceptRequest, [], {#requestId: requestId}),
              ),
            ),
          )
          as _i20.Future<_i16.FriendshipResponseEntity>);

  @override
  _i20.Future<_i16.FriendshipResponseEntity> rejectRequest({
    required String? requestId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rejectRequest, [], {#requestId: requestId}),
            returnValue: _i20.Future<_i16.FriendshipResponseEntity>.value(
              _FakeFriendshipResponseEntity_14(
                this,
                Invocation.method(#rejectRequest, [], {#requestId: requestId}),
              ),
            ),
          )
          as _i20.Future<_i16.FriendshipResponseEntity>);

  @override
  _i20.Future<List<_i16.FriendRequestEntity>> getPendingRequests() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingRequests, []),
            returnValue: _i20.Future<List<_i16.FriendRequestEntity>>.value(
              <_i16.FriendRequestEntity>[],
            ),
          )
          as _i20.Future<List<_i16.FriendRequestEntity>>);

  @override
  _i20.Future<List<_i16.FriendRequestEntity>> getSentRequests() =>
      (super.noSuchMethod(
            Invocation.method(#getSentRequests, []),
            returnValue: _i20.Future<List<_i16.FriendRequestEntity>>.value(
              <_i16.FriendRequestEntity>[],
            ),
          )
          as _i20.Future<List<_i16.FriendRequestEntity>>);

  @override
  _i20.Future<List<_i16.FriendEntity>> getFriends() =>
      (super.noSuchMethod(
            Invocation.method(#getFriends, []),
            returnValue: _i20.Future<List<_i16.FriendEntity>>.value(
              <_i16.FriendEntity>[],
            ),
          )
          as _i20.Future<List<_i16.FriendEntity>>);

  @override
  _i20.Future<List<_i16.FriendEntity>> getUserFriends({
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUserFriends, [], {#userId: userId}),
            returnValue: _i20.Future<List<_i16.FriendEntity>>.value(
              <_i16.FriendEntity>[],
            ),
          )
          as _i20.Future<List<_i16.FriendEntity>>);

  @override
  _i20.Future<_i16.FriendshipStatusEntity> isFriend({
    required String? userAId,
    required String? userBId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#isFriend, [], {
              #userAId: userAId,
              #userBId: userBId,
            }),
            returnValue: _i20.Future<_i16.FriendshipStatusEntity>.value(
              _FakeFriendshipStatusEntity_15(
                this,
                Invocation.method(#isFriend, [], {
                  #userAId: userAId,
                  #userBId: userBId,
                }),
              ),
            ),
          )
          as _i20.Future<_i16.FriendshipStatusEntity>);

  @override
  _i20.Future<List<String>> getFriendIds() =>
      (super.noSuchMethod(
            Invocation.method(#getFriendIds, []),
            returnValue: _i20.Future<List<String>>.value(<String>[]),
          )
          as _i20.Future<List<String>>);
}

/// A class which mocks [FriendshipRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFriendshipRemoteDataSource extends _i1.Mock
    implements _i54.FriendshipRemoteDataSource {
  MockFriendshipRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i20.Future<_i17.FriendshipResponseModel> sendRequest({
    required String? toUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendRequest, [], {#toUserId: toUserId}),
            returnValue: _i20.Future<_i17.FriendshipResponseModel>.value(
              _FakeFriendshipResponseModel_16(
                this,
                Invocation.method(#sendRequest, [], {#toUserId: toUserId}),
              ),
            ),
          )
          as _i20.Future<_i17.FriendshipResponseModel>);

  @override
  _i20.Future<_i17.FriendshipResponseModel> acceptRequest({
    required String? requestId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#acceptRequest, [], {#requestId: requestId}),
            returnValue: _i20.Future<_i17.FriendshipResponseModel>.value(
              _FakeFriendshipResponseModel_16(
                this,
                Invocation.method(#acceptRequest, [], {#requestId: requestId}),
              ),
            ),
          )
          as _i20.Future<_i17.FriendshipResponseModel>);

  @override
  _i20.Future<_i17.FriendshipResponseModel> rejectRequest({
    required String? requestId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rejectRequest, [], {#requestId: requestId}),
            returnValue: _i20.Future<_i17.FriendshipResponseModel>.value(
              _FakeFriendshipResponseModel_16(
                this,
                Invocation.method(#rejectRequest, [], {#requestId: requestId}),
              ),
            ),
          )
          as _i20.Future<_i17.FriendshipResponseModel>);

  @override
  _i20.Future<List<_i17.FriendRequestModel>> getPendingRequests() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingRequests, []),
            returnValue: _i20.Future<List<_i17.FriendRequestModel>>.value(
              <_i17.FriendRequestModel>[],
            ),
          )
          as _i20.Future<List<_i17.FriendRequestModel>>);

  @override
  _i20.Future<List<_i17.FriendRequestModel>> getSentRequests() =>
      (super.noSuchMethod(
            Invocation.method(#getSentRequests, []),
            returnValue: _i20.Future<List<_i17.FriendRequestModel>>.value(
              <_i17.FriendRequestModel>[],
            ),
          )
          as _i20.Future<List<_i17.FriendRequestModel>>);

  @override
  _i20.Future<List<_i17.FriendModel>> getFriends() =>
      (super.noSuchMethod(
            Invocation.method(#getFriends, []),
            returnValue: _i20.Future<List<_i17.FriendModel>>.value(
              <_i17.FriendModel>[],
            ),
          )
          as _i20.Future<List<_i17.FriendModel>>);

  @override
  _i20.Future<List<_i17.FriendModel>> getUserFriends({
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUserFriends, [], {#userId: userId}),
            returnValue: _i20.Future<List<_i17.FriendModel>>.value(
              <_i17.FriendModel>[],
            ),
          )
          as _i20.Future<List<_i17.FriendModel>>);

  @override
  _i20.Future<_i17.FriendshipStatusModel> isFriend({
    required String? userAId,
    required String? userBId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#isFriend, [], {
              #userAId: userAId,
              #userBId: userBId,
            }),
            returnValue: _i20.Future<_i17.FriendshipStatusModel>.value(
              _FakeFriendshipStatusModel_17(
                this,
                Invocation.method(#isFriend, [], {
                  #userAId: userAId,
                  #userBId: userBId,
                }),
              ),
            ),
          )
          as _i20.Future<_i17.FriendshipStatusModel>);

  @override
  _i20.Future<List<String>> getFriendIds() =>
      (super.noSuchMethod(
            Invocation.method(#getFriendIds, []),
            returnValue: _i20.Future<List<String>>.value(<String>[]),
          )
          as _i20.Future<List<String>>);
}
