// Mocks generated by Mockito 5.4.6 from annotations
// in social_app/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;

import 'package:dartz/dartz.dart' as _i5;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:social_app/core/core.dart' as _i9;
import 'package:social_app/core/entities/pagination_param.dart' as _i26;
import 'package:social_app/core/network/base_response.dart' as _i6;
import 'package:social_app/core/network/network_info.dart' as _i3;
import 'package:social_app/features/auth/data/datasources/auth_local_data_source.dart'
    as _i4;
import 'package:social_app/features/auth/data/datasources/auth_remote_data_source.dart'
    as _i15;
import 'package:social_app/features/auth/data/models/auth_tokens_model.dart'
    as _i17;
import 'package:social_app/features/auth/data/models/user_model.dart' as _i16;
import 'package:social_app/features/auth/domain/entities/auth_tokens.dart'
    as _i14;
import 'package:social_app/features/auth/domain/entities/user.dart' as _i13;
import 'package:social_app/features/auth/domain/repositories/auth_repository.dart'
    as _i12;
import 'package:social_app/features/comment/data/datasources/comment_remote_data_source.dart'
    as _i27;
import 'package:social_app/features/comment/data/models/comment_model.dart'
    as _i28;
import 'package:social_app/features/comment/domain/entities/comment_entity.dart'
    as _i25;
import 'package:social_app/features/comment/domain/repositories/comment_repository.dart'
    as _i24;
import 'package:social_app/features/friendship/data/datasources/friendship_remote_data_source.dart'
    as _i35;
import 'package:social_app/features/friendship/data/models/friendship_model.dart'
    as _i8;
import 'package:social_app/features/friendship/domain/entities/friendship_entity.dart'
    as _i34;
import 'package:social_app/features/friendship/domain/repositories/friendship_repository.dart'
    as _i33;
import 'package:social_app/features/post/data/datasources/post_local_data_source.dart'
    as _i23;
import 'package:social_app/features/post/data/datasources/post_remote_data_source.dart'
    as _i21;
import 'package:social_app/features/post/data/models/post_model.dart' as _i22;
import 'package:social_app/features/post/domain/entities/post_entity.dart'
    as _i19;
import 'package:social_app/features/post/domain/entities/post_enum.dart'
    as _i20;
import 'package:social_app/features/post/domain/repositories/post_repository.dart'
    as _i18;
import 'package:social_app/features/reaction/data/datasources/reaction_remote_data_source.dart'
    as _i32;
import 'package:social_app/features/reaction/data/models/reaction_model.dart'
    as _i7;
import 'package:social_app/features/reaction/domain/entities/reaction_entity.dart'
    as _i30;
import 'package:social_app/features/reaction/domain/entities/reaction_enums.dart'
    as _i31;
import 'package:social_app/features/reaction/domain/repositories/reaction_repository.dart'
    as _i29;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNetworkInfo_1 extends _i1.SmartFake implements _i3.NetworkInfo {
  _FakeNetworkInfo_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthLocalDataSource_2 extends _i1.SmartFake
    implements _i4.AuthLocalDataSource {
  _FakeAuthLocalDataSource_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_3<L, R> extends _i1.SmartFake implements _i5.Either<L, R> {
  _FakeEither_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseResponse_4<T> extends _i1.SmartFake
    implements _i6.BaseResponse<T> {
  _FakeBaseResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReactionResponseModel_5 extends _i1.SmartFake
    implements _i7.ReactionResponseModel {
  _FakeReactionResponseModel_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFriendshipResponseModel_6 extends _i1.SmartFake
    implements _i8.FriendshipResponseModel {
  _FakeFriendshipResponseModel_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFriendshipStatusModel_7 extends _i1.SmartFake
    implements _i8.FriendshipStatusModel {
  _FakeFriendshipStatusModel_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i9.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get httpClient =>
      (super.noSuchMethod(
            Invocation.getter(#httpClient),
            returnValue: _FakeClient_0(this, Invocation.getter(#httpClient)),
          )
          as _i2.Client);

  @override
  _i3.NetworkInfo get networkInfo =>
      (super.noSuchMethod(
            Invocation.getter(#networkInfo),
            returnValue: _FakeNetworkInfo_1(
              this,
              Invocation.getter(#networkInfo),
            ),
          )
          as _i3.NetworkInfo);

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i4.AuthLocalDataSource get tokenProvider =>
      (super.noSuchMethod(
            Invocation.getter(#tokenProvider),
            returnValue: _FakeAuthLocalDataSource_2(
              this,
              Invocation.getter(#tokenProvider),
            ),
          )
          as _i4.AuthLocalDataSource);

  @override
  _i11.Future<Map<String, dynamic>> request({
    required String? method,
    required String? endpoint,
    Map<String, dynamic>? body,
    Map<String, String>? query,
    String? token,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#request, [], {
              #method: method,
              #endpoint: endpoint,
              #body: body,
              #query: query,
              #token: token,
              #headers: headers,
            }),
            returnValue: _i11.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i11.Future<Map<String, dynamic>>);

  @override
  _i11.Future<Map<String, dynamic>?> upload({
    required String? endpoint,
    required _i2.MultipartRequest? request,
    String? token,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upload, [], {
              #endpoint: endpoint,
              #request: request,
              #token: token,
              #headers: headers,
            }),
            returnValue: _i11.Future<Map<String, dynamic>?>.value(),
          )
          as _i11.Future<Map<String, dynamic>?>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i3.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Stream<bool> get onConnectivityChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onConnectivityChanged),
            returnValue: _i11.Stream<bool>.empty(),
          )
          as _i11.Stream<bool>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i12.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i5.Either<_i9.Failure, _i13.User>> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue: _i11.Future<_i5.Either<_i9.Failure, _i13.User>>.value(
              _FakeEither_3<_i9.Failure, _i13.User>(
                this,
                Invocation.method(#login, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i11.Future<_i5.Either<_i9.Failure, _i13.User>>);

  @override
  _i11.Future<_i5.Either<_i9.Failure, _i13.User>> register({
    required String? email,
    required String? username,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #email: email,
              #username: username,
              #password: password,
            }),
            returnValue: _i11.Future<_i5.Either<_i9.Failure, _i13.User>>.value(
              _FakeEither_3<_i9.Failure, _i13.User>(
                this,
                Invocation.method(#register, [], {
                  #email: email,
                  #username: username,
                  #password: password,
                }),
              ),
            ),
          )
          as _i11.Future<_i5.Either<_i9.Failure, _i13.User>>);

  @override
  _i11.Future<_i5.Either<_i9.Failure, void>> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i11.Future<_i5.Either<_i9.Failure, void>>.value(
              _FakeEither_3<_i9.Failure, void>(
                this,
                Invocation.method(#logout, []),
              ),
            ),
          )
          as _i11.Future<_i5.Either<_i9.Failure, void>>);

  @override
  _i11.Future<_i5.Either<_i9.Failure, _i13.User>> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i11.Future<_i5.Either<_i9.Failure, _i13.User>>.value(
              _FakeEither_3<_i9.Failure, _i13.User>(
                this,
                Invocation.method(#getCurrentUser, []),
              ),
            ),
          )
          as _i11.Future<_i5.Either<_i9.Failure, _i13.User>>);

  @override
  _i11.Future<bool> isAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticated, []),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<_i14.AuthTokens?> getAuthTokens() =>
      (super.noSuchMethod(
            Invocation.method(#getAuthTokens, []),
            returnValue: _i11.Future<_i14.AuthTokens?>.value(),
          )
          as _i11.Future<_i14.AuthTokens?>);

  @override
  _i11.Future<_i5.Either<_i9.Failure, _i14.AuthTokens>> refreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, []),
            returnValue:
                _i11.Future<_i5.Either<_i9.Failure, _i14.AuthTokens>>.value(
                  _FakeEither_3<_i9.Failure, _i14.AuthTokens>(
                    this,
                    Invocation.method(#refreshToken, []),
                  ),
                ),
          )
          as _i11.Future<_i5.Either<_i9.Failure, _i14.AuthTokens>>);

  @override
  _i11.Future<_i5.Either<_i9.Failure, _i13.User>> updateProfile({
    String? displayName,
    String? bio,
    String? avatarUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #displayName: displayName,
              #bio: bio,
              #avatarUrl: avatarUrl,
            }),
            returnValue: _i11.Future<_i5.Either<_i9.Failure, _i13.User>>.value(
              _FakeEither_3<_i9.Failure, _i13.User>(
                this,
                Invocation.method(#updateProfile, [], {
                  #displayName: displayName,
                  #bio: bio,
                  #avatarUrl: avatarUrl,
                }),
              ),
            ),
          )
          as _i11.Future<_i5.Either<_i9.Failure, _i13.User>>);

  @override
  _i11.Future<_i5.Either<_i9.Failure, void>> changePassword({
    required String? currentPassword,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [], {
              #currentPassword: currentPassword,
              #newPassword: newPassword,
            }),
            returnValue: _i11.Future<_i5.Either<_i9.Failure, void>>.value(
              _FakeEither_3<_i9.Failure, void>(
                this,
                Invocation.method(#changePassword, [], {
                  #currentPassword: currentPassword,
                  #newPassword: newPassword,
                }),
              ),
            ),
          )
          as _i11.Future<_i5.Either<_i9.Failure, void>>);

  @override
  _i11.Future<_i5.Either<_i9.Failure, void>> requestPasswordReset({
    required String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#requestPasswordReset, [], {#email: email}),
            returnValue: _i11.Future<_i5.Either<_i9.Failure, void>>.value(
              _FakeEither_3<_i9.Failure, void>(
                this,
                Invocation.method(#requestPasswordReset, [], {#email: email}),
              ),
            ),
          )
          as _i11.Future<_i5.Either<_i9.Failure, void>>);

  @override
  _i11.Future<_i5.Either<_i9.Failure, void>> resetPassword({
    required String? token,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {
              #token: token,
              #newPassword: newPassword,
            }),
            returnValue: _i11.Future<_i5.Either<_i9.Failure, void>>.value(
              _FakeEither_3<_i9.Failure, void>(
                this,
                Invocation.method(#resetPassword, [], {
                  #token: token,
                  #newPassword: newPassword,
                }),
              ),
            ),
          )
          as _i11.Future<_i5.Either<_i9.Failure, void>>);

  @override
  _i11.Future<_i5.Either<_i9.Failure, void>> verifyEmail({
    required String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyEmail, [], {#token: token}),
            returnValue: _i11.Future<_i5.Either<_i9.Failure, void>>.value(
              _FakeEither_3<_i9.Failure, void>(
                this,
                Invocation.method(#verifyEmail, [], {#token: token}),
              ),
            ),
          )
          as _i11.Future<_i5.Either<_i9.Failure, void>>);
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i15.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i6.BaseResponse<Map<String, dynamic>>> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue:
                _i11.Future<_i6.BaseResponse<Map<String, dynamic>>>.value(
                  _FakeBaseResponse_4<Map<String, dynamic>>(
                    this,
                    Invocation.method(#login, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i11.Future<_i6.BaseResponse<Map<String, dynamic>>>);

  @override
  _i11.Future<_i6.BaseResponse<Map<String, dynamic>>> register({
    required String? email,
    required String? username,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #email: email,
              #username: username,
              #password: password,
            }),
            returnValue:
                _i11.Future<_i6.BaseResponse<Map<String, dynamic>>>.value(
                  _FakeBaseResponse_4<Map<String, dynamic>>(
                    this,
                    Invocation.method(#register, [], {
                      #email: email,
                      #username: username,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i11.Future<_i6.BaseResponse<Map<String, dynamic>>>);

  @override
  _i11.Future<_i6.BaseResponse<void>> logout(dynamic userId) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [userId]),
            returnValue: _i11.Future<_i6.BaseResponse<void>>.value(
              _FakeBaseResponse_4<void>(
                this,
                Invocation.method(#logout, [userId]),
              ),
            ),
          )
          as _i11.Future<_i6.BaseResponse<void>>);

  @override
  _i11.Future<_i6.BaseResponse<_i16.UserModel>> getCurrentUser({
    required String? accessToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, [], {#accessToken: accessToken}),
            returnValue: _i11.Future<_i6.BaseResponse<_i16.UserModel>>.value(
              _FakeBaseResponse_4<_i16.UserModel>(
                this,
                Invocation.method(#getCurrentUser, [], {
                  #accessToken: accessToken,
                }),
              ),
            ),
          )
          as _i11.Future<_i6.BaseResponse<_i16.UserModel>>);

  @override
  _i11.Future<_i6.BaseResponse<_i16.UserModel>> updateProfile({
    required String? accessToken,
    String? displayName,
    String? bio,
    String? avatarUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #accessToken: accessToken,
              #displayName: displayName,
              #bio: bio,
              #avatarUrl: avatarUrl,
            }),
            returnValue: _i11.Future<_i6.BaseResponse<_i16.UserModel>>.value(
              _FakeBaseResponse_4<_i16.UserModel>(
                this,
                Invocation.method(#updateProfile, [], {
                  #accessToken: accessToken,
                  #displayName: displayName,
                  #bio: bio,
                  #avatarUrl: avatarUrl,
                }),
              ),
            ),
          )
          as _i11.Future<_i6.BaseResponse<_i16.UserModel>>);

  @override
  _i11.Future<_i6.BaseResponse<void>> changePassword({
    required String? accessToken,
    required String? currentPassword,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [], {
              #accessToken: accessToken,
              #currentPassword: currentPassword,
              #newPassword: newPassword,
            }),
            returnValue: _i11.Future<_i6.BaseResponse<void>>.value(
              _FakeBaseResponse_4<void>(
                this,
                Invocation.method(#changePassword, [], {
                  #accessToken: accessToken,
                  #currentPassword: currentPassword,
                  #newPassword: newPassword,
                }),
              ),
            ),
          )
          as _i11.Future<_i6.BaseResponse<void>>);

  @override
  _i11.Future<_i6.BaseResponse<void>> requestPasswordReset({
    required String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#requestPasswordReset, [], {#email: email}),
            returnValue: _i11.Future<_i6.BaseResponse<void>>.value(
              _FakeBaseResponse_4<void>(
                this,
                Invocation.method(#requestPasswordReset, [], {#email: email}),
              ),
            ),
          )
          as _i11.Future<_i6.BaseResponse<void>>);

  @override
  _i11.Future<_i6.BaseResponse<void>> resetPassword({
    required String? token,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {
              #token: token,
              #newPassword: newPassword,
            }),
            returnValue: _i11.Future<_i6.BaseResponse<void>>.value(
              _FakeBaseResponse_4<void>(
                this,
                Invocation.method(#resetPassword, [], {
                  #token: token,
                  #newPassword: newPassword,
                }),
              ),
            ),
          )
          as _i11.Future<_i6.BaseResponse<void>>);

  @override
  _i11.Future<_i6.BaseResponse<void>> verifyEmail({required String? token}) =>
      (super.noSuchMethod(
            Invocation.method(#verifyEmail, [], {#token: token}),
            returnValue: _i11.Future<_i6.BaseResponse<void>>.value(
              _FakeBaseResponse_4<void>(
                this,
                Invocation.method(#verifyEmail, [], {#token: token}),
              ),
            ),
          )
          as _i11.Future<_i6.BaseResponse<void>>);

  @override
  _i11.Future<_i6.BaseResponse<Map<String, dynamic>>> refreshToken({
    required String? refreshToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, [], {#refreshToken: refreshToken}),
            returnValue:
                _i11.Future<_i6.BaseResponse<Map<String, dynamic>>>.value(
                  _FakeBaseResponse_4<Map<String, dynamic>>(
                    this,
                    Invocation.method(#refreshToken, [], {
                      #refreshToken: refreshToken,
                    }),
                  ),
                ),
          )
          as _i11.Future<_i6.BaseResponse<Map<String, dynamic>>>);
}

/// A class which mocks [AuthLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDataSource extends _i1.Mock
    implements _i4.AuthLocalDataSource {
  MockAuthLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<void> cacheUser(_i16.UserModel? user) =>
      (super.noSuchMethod(
            Invocation.method(#cacheUser, [user]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<_i16.UserModel?> getCachedUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedUser, []),
            returnValue: _i11.Future<_i16.UserModel?>.value(),
          )
          as _i11.Future<_i16.UserModel?>);

  @override
  _i11.Future<void> clearCachedUser() =>
      (super.noSuchMethod(
            Invocation.method(#clearCachedUser, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> cacheTokens(_i17.AuthTokensModel? tokens) =>
      (super.noSuchMethod(
            Invocation.method(#cacheTokens, [tokens]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<_i17.AuthTokensModel?> getCachedTokens() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedTokens, []),
            returnValue: _i11.Future<_i17.AuthTokensModel?>.value(),
          )
          as _i11.Future<_i17.AuthTokensModel?>);

  @override
  _i11.Future<void> clearCachedTokens() =>
      (super.noSuchMethod(
            Invocation.method(#clearCachedTokens, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> clearAllData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllData, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}

/// A class which mocks [PostRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostRepository extends _i1.Mock implements _i18.PostRepository {
  MockPostRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i5.Either<_i9.Failure, _i19.PostEntity>> createPost({
    required String? content,
    required _i20.PostVisibility? visibility,
    required _i20.PostType? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPost, [], {
              #content: content,
              #visibility: visibility,
              #type: type,
            }),
            returnValue:
                _i11.Future<_i5.Either<_i9.Failure, _i19.PostEntity>>.value(
                  _FakeEither_3<_i9.Failure, _i19.PostEntity>(
                    this,
                    Invocation.method(#createPost, [], {
                      #content: content,
                      #visibility: visibility,
                      #type: type,
                    }),
                  ),
                ),
          )
          as _i11.Future<_i5.Either<_i9.Failure, _i19.PostEntity>>);

  @override
  _i11.Future<_i5.Either<_i9.Failure, _i19.PostEntity>> updatePost({
    required String? postId,
    required String? content,
    required _i20.PostVisibility? visibility,
    required _i20.PostType? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePost, [], {
              #postId: postId,
              #content: content,
              #visibility: visibility,
              #type: type,
            }),
            returnValue:
                _i11.Future<_i5.Either<_i9.Failure, _i19.PostEntity>>.value(
                  _FakeEither_3<_i9.Failure, _i19.PostEntity>(
                    this,
                    Invocation.method(#updatePost, [], {
                      #postId: postId,
                      #content: content,
                      #visibility: visibility,
                      #type: type,
                    }),
                  ),
                ),
          )
          as _i11.Future<_i5.Either<_i9.Failure, _i19.PostEntity>>);

  @override
  _i11.Future<_i5.Either<_i9.Failure, void>> deletePost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePost, [postId]),
            returnValue: _i11.Future<_i5.Either<_i9.Failure, void>>.value(
              _FakeEither_3<_i9.Failure, void>(
                this,
                Invocation.method(#deletePost, [postId]),
              ),
            ),
          )
          as _i11.Future<_i5.Either<_i9.Failure, void>>);

  @override
  _i11.Future<_i5.Either<_i9.Failure, _i19.PostEntity>> getPost(
    String? postId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPost, [postId]),
            returnValue:
                _i11.Future<_i5.Either<_i9.Failure, _i19.PostEntity>>.value(
                  _FakeEither_3<_i9.Failure, _i19.PostEntity>(
                    this,
                    Invocation.method(#getPost, [postId]),
                  ),
                ),
          )
          as _i11.Future<_i5.Either<_i9.Failure, _i19.PostEntity>>);

  @override
  _i11.Future<_i5.Either<_i9.Failure, List<_i19.PostEntity>>> getHomePost() =>
      (super.noSuchMethod(
            Invocation.method(#getHomePost, []),
            returnValue:
                _i11.Future<
                  _i5.Either<_i9.Failure, List<_i19.PostEntity>>
                >.value(
                  _FakeEither_3<_i9.Failure, List<_i19.PostEntity>>(
                    this,
                    Invocation.method(#getHomePost, []),
                  ),
                ),
          )
          as _i11.Future<_i5.Either<_i9.Failure, List<_i19.PostEntity>>>);

  @override
  _i11.Future<_i5.Either<_i9.Failure, List<_i19.PostEntity>>> getPostsByUser(
    String? viewerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPostsByUser, [viewerId]),
            returnValue:
                _i11.Future<
                  _i5.Either<_i9.Failure, List<_i19.PostEntity>>
                >.value(
                  _FakeEither_3<_i9.Failure, List<_i19.PostEntity>>(
                    this,
                    Invocation.method(#getPostsByUser, [viewerId]),
                  ),
                ),
          )
          as _i11.Future<_i5.Either<_i9.Failure, List<_i19.PostEntity>>>);
}

/// A class which mocks [PostRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostRemoteDataSource extends _i1.Mock
    implements _i21.PostRemoteDataSource {
  MockPostRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i6.BaseResponse<_i22.PostModel>> createPost({
    required String? content,
    required String? visibility,
    required String? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPost, [], {
              #content: content,
              #visibility: visibility,
              #type: type,
            }),
            returnValue: _i11.Future<_i6.BaseResponse<_i22.PostModel>>.value(
              _FakeBaseResponse_4<_i22.PostModel>(
                this,
                Invocation.method(#createPost, [], {
                  #content: content,
                  #visibility: visibility,
                  #type: type,
                }),
              ),
            ),
          )
          as _i11.Future<_i6.BaseResponse<_i22.PostModel>>);

  @override
  _i11.Future<_i6.BaseResponse<_i22.PostModel>> updatePost({
    required String? postId,
    required String? content,
    required String? visibility,
    required String? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePost, [], {
              #postId: postId,
              #content: content,
              #visibility: visibility,
              #type: type,
            }),
            returnValue: _i11.Future<_i6.BaseResponse<_i22.PostModel>>.value(
              _FakeBaseResponse_4<_i22.PostModel>(
                this,
                Invocation.method(#updatePost, [], {
                  #postId: postId,
                  #content: content,
                  #visibility: visibility,
                  #type: type,
                }),
              ),
            ),
          )
          as _i11.Future<_i6.BaseResponse<_i22.PostModel>>);

  @override
  _i11.Future<_i6.BaseResponse<void>> deletePost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePost, [postId]),
            returnValue: _i11.Future<_i6.BaseResponse<void>>.value(
              _FakeBaseResponse_4<void>(
                this,
                Invocation.method(#deletePost, [postId]),
              ),
            ),
          )
          as _i11.Future<_i6.BaseResponse<void>>);

  @override
  _i11.Future<_i6.BaseResponse<_i22.PostModel>> getPost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#getPost, [postId]),
            returnValue: _i11.Future<_i6.BaseResponse<_i22.PostModel>>.value(
              _FakeBaseResponse_4<_i22.PostModel>(
                this,
                Invocation.method(#getPost, [postId]),
              ),
            ),
          )
          as _i11.Future<_i6.BaseResponse<_i22.PostModel>>);

  @override
  _i11.Future<_i6.BaseResponse<List<_i22.PostModel>>> getHomePost() =>
      (super.noSuchMethod(
            Invocation.method(#getHomePost, []),
            returnValue:
                _i11.Future<_i6.BaseResponse<List<_i22.PostModel>>>.value(
                  _FakeBaseResponse_4<List<_i22.PostModel>>(
                    this,
                    Invocation.method(#getHomePost, []),
                  ),
                ),
          )
          as _i11.Future<_i6.BaseResponse<List<_i22.PostModel>>>);

  @override
  _i11.Future<_i6.BaseResponse<List<_i22.PostModel>>> getPostsByUser(
    String? viewerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPostsByUser, [viewerId]),
            returnValue:
                _i11.Future<_i6.BaseResponse<List<_i22.PostModel>>>.value(
                  _FakeBaseResponse_4<List<_i22.PostModel>>(
                    this,
                    Invocation.method(#getPostsByUser, [viewerId]),
                  ),
                ),
          )
          as _i11.Future<_i6.BaseResponse<List<_i22.PostModel>>>);
}

/// A class which mocks [PostLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostLocalDataSource extends _i1.Mock
    implements _i23.PostLocalDataSource {
  MockPostLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<void> cachePosts(List<_i22.PostModel>? posts) =>
      (super.noSuchMethod(
            Invocation.method(#cachePosts, [posts]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<List<_i22.PostModel>?> getCachedPosts() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedPosts, []),
            returnValue: _i11.Future<List<_i22.PostModel>?>.value(),
          )
          as _i11.Future<List<_i22.PostModel>?>);

  @override
  _i11.Future<void> clearCachedPosts() =>
      (super.noSuchMethod(
            Invocation.method(#clearCachedPosts, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}

/// A class which mocks [CommentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommentRepository extends _i1.Mock implements _i24.CommentRepository {
  MockCommentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i5.Either<_i9.Failure, _i25.CommentEntity>> createComment({
    required String? postId,
    required String? content,
    String? parentCommentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createComment, [], {
              #postId: postId,
              #content: content,
              #parentCommentId: parentCommentId,
            }),
            returnValue:
                _i11.Future<_i5.Either<_i9.Failure, _i25.CommentEntity>>.value(
                  _FakeEither_3<_i9.Failure, _i25.CommentEntity>(
                    this,
                    Invocation.method(#createComment, [], {
                      #postId: postId,
                      #content: content,
                      #parentCommentId: parentCommentId,
                    }),
                  ),
                ),
          )
          as _i11.Future<_i5.Either<_i9.Failure, _i25.CommentEntity>>);

  @override
  _i11.Future<_i5.Either<_i9.Failure, _i25.CommentEntity>> updateComment({
    required String? commentId,
    required String? content,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateComment, [], {
              #commentId: commentId,
              #content: content,
            }),
            returnValue:
                _i11.Future<_i5.Either<_i9.Failure, _i25.CommentEntity>>.value(
                  _FakeEither_3<_i9.Failure, _i25.CommentEntity>(
                    this,
                    Invocation.method(#updateComment, [], {
                      #commentId: commentId,
                      #content: content,
                    }),
                  ),
                ),
          )
          as _i11.Future<_i5.Either<_i9.Failure, _i25.CommentEntity>>);

  @override
  _i11.Future<_i5.Either<_i9.Failure, void>> deleteComment(String? commentId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteComment, [commentId]),
            returnValue: _i11.Future<_i5.Either<_i9.Failure, void>>.value(
              _FakeEither_3<_i9.Failure, void>(
                this,
                Invocation.method(#deleteComment, [commentId]),
              ),
            ),
          )
          as _i11.Future<_i5.Either<_i9.Failure, void>>);

  @override
  _i11.Future<_i5.Either<_i9.Failure, List<_i25.CommentEntity>>>
  getCommentsByPost({
    required String? postId,
    required _i26.PaginationParams? query,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCommentsByPost, [], {
              #postId: postId,
              #query: query,
            }),
            returnValue:
                _i11.Future<
                  _i5.Either<_i9.Failure, List<_i25.CommentEntity>>
                >.value(
                  _FakeEither_3<_i9.Failure, List<_i25.CommentEntity>>(
                    this,
                    Invocation.method(#getCommentsByPost, [], {
                      #postId: postId,
                      #query: query,
                    }),
                  ),
                ),
          )
          as _i11.Future<_i5.Either<_i9.Failure, List<_i25.CommentEntity>>>);

  @override
  _i11.Future<_i5.Either<_i9.Failure, List<_i25.CommentEntity>>> getReplies({
    required String? commentId,
    required _i26.PaginationParams? query,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getReplies, [], {
              #commentId: commentId,
              #query: query,
            }),
            returnValue:
                _i11.Future<
                  _i5.Either<_i9.Failure, List<_i25.CommentEntity>>
                >.value(
                  _FakeEither_3<_i9.Failure, List<_i25.CommentEntity>>(
                    this,
                    Invocation.method(#getReplies, [], {
                      #commentId: commentId,
                      #query: query,
                    }),
                  ),
                ),
          )
          as _i11.Future<_i5.Either<_i9.Failure, List<_i25.CommentEntity>>>);
}

/// A class which mocks [CommentRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommentRemoteDataSource extends _i1.Mock
    implements _i27.CommentRemoteDataSource {
  MockCommentRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i6.BaseResponse<_i28.CommentModel>> createComment({
    required String? postId,
    required String? content,
    String? parentCommentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createComment, [], {
              #postId: postId,
              #content: content,
              #parentCommentId: parentCommentId,
            }),
            returnValue: _i11.Future<_i6.BaseResponse<_i28.CommentModel>>.value(
              _FakeBaseResponse_4<_i28.CommentModel>(
                this,
                Invocation.method(#createComment, [], {
                  #postId: postId,
                  #content: content,
                  #parentCommentId: parentCommentId,
                }),
              ),
            ),
          )
          as _i11.Future<_i6.BaseResponse<_i28.CommentModel>>);

  @override
  _i11.Future<_i6.BaseResponse<_i28.CommentModel>> updateComment({
    required String? commentId,
    required String? content,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateComment, [], {
              #commentId: commentId,
              #content: content,
            }),
            returnValue: _i11.Future<_i6.BaseResponse<_i28.CommentModel>>.value(
              _FakeBaseResponse_4<_i28.CommentModel>(
                this,
                Invocation.method(#updateComment, [], {
                  #commentId: commentId,
                  #content: content,
                }),
              ),
            ),
          )
          as _i11.Future<_i6.BaseResponse<_i28.CommentModel>>);

  @override
  _i11.Future<_i6.BaseResponse<void>> deleteComment(String? commentId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteComment, [commentId]),
            returnValue: _i11.Future<_i6.BaseResponse<void>>.value(
              _FakeBaseResponse_4<void>(
                this,
                Invocation.method(#deleteComment, [commentId]),
              ),
            ),
          )
          as _i11.Future<_i6.BaseResponse<void>>);

  @override
  _i11.Future<_i6.BaseResponse<List<_i28.CommentModel>>> getCommentByPost({
    required String? postId,
    _i26.PaginationParams? pagination,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCommentByPost, [], {
              #postId: postId,
              #pagination: pagination,
            }),
            returnValue:
                _i11.Future<_i6.BaseResponse<List<_i28.CommentModel>>>.value(
                  _FakeBaseResponse_4<List<_i28.CommentModel>>(
                    this,
                    Invocation.method(#getCommentByPost, [], {
                      #postId: postId,
                      #pagination: pagination,
                    }),
                  ),
                ),
          )
          as _i11.Future<_i6.BaseResponse<List<_i28.CommentModel>>>);

  @override
  _i11.Future<_i6.BaseResponse<List<_i28.CommentModel>>> getReplies({
    required String? commentId,
    _i26.PaginationParams? pagination,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getReplies, [], {
              #commentId: commentId,
              #pagination: pagination,
            }),
            returnValue:
                _i11.Future<_i6.BaseResponse<List<_i28.CommentModel>>>.value(
                  _FakeBaseResponse_4<List<_i28.CommentModel>>(
                    this,
                    Invocation.method(#getReplies, [], {
                      #commentId: commentId,
                      #pagination: pagination,
                    }),
                  ),
                ),
          )
          as _i11.Future<_i6.BaseResponse<List<_i28.CommentModel>>>);
}

/// A class which mocks [ReactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockReactionRepository extends _i1.Mock
    implements _i29.ReactionRepository {
  MockReactionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i5.Either<_i9.Failure, _i30.ReactionResponseEntity>> react({
    required _i31.ReactionTargetType? targetType,
    required String? targetId,
    required _i31.ReactionType? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#react, [], {
              #targetType: targetType,
              #targetId: targetId,
              #type: type,
            }),
            returnValue:
                _i11.Future<
                  _i5.Either<_i9.Failure, _i30.ReactionResponseEntity>
                >.value(
                  _FakeEither_3<_i9.Failure, _i30.ReactionResponseEntity>(
                    this,
                    Invocation.method(#react, [], {
                      #targetType: targetType,
                      #targetId: targetId,
                      #type: type,
                    }),
                  ),
                ),
          )
          as _i11.Future<_i5.Either<_i9.Failure, _i30.ReactionResponseEntity>>);

  @override
  _i11.Future<_i5.Either<_i9.Failure, List<_i30.ReactionSummaryEntity>>>
  getReactionSummary({
    required _i31.ReactionTargetType? targetType,
    required String? targetId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getReactionSummary, [], {
              #targetType: targetType,
              #targetId: targetId,
            }),
            returnValue:
                _i11.Future<
                  _i5.Either<_i9.Failure, List<_i30.ReactionSummaryEntity>>
                >.value(
                  _FakeEither_3<_i9.Failure, List<_i30.ReactionSummaryEntity>>(
                    this,
                    Invocation.method(#getReactionSummary, [], {
                      #targetType: targetType,
                      #targetId: targetId,
                    }),
                  ),
                ),
          )
          as _i11.Future<
            _i5.Either<_i9.Failure, List<_i30.ReactionSummaryEntity>>
          >);

  @override
  _i11.Future<_i5.Either<_i9.Failure, _i30.ReactionEntity?>> getUserReaction({
    required _i31.ReactionTargetType? targetType,
    required String? targetId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUserReaction, [], {
              #targetType: targetType,
              #targetId: targetId,
            }),
            returnValue:
                _i11.Future<
                  _i5.Either<_i9.Failure, _i30.ReactionEntity?>
                >.value(
                  _FakeEither_3<_i9.Failure, _i30.ReactionEntity?>(
                    this,
                    Invocation.method(#getUserReaction, [], {
                      #targetType: targetType,
                      #targetId: targetId,
                    }),
                  ),
                ),
          )
          as _i11.Future<_i5.Either<_i9.Failure, _i30.ReactionEntity?>>);
}

/// A class which mocks [ReactionRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockReactionRemoteDataSource extends _i1.Mock
    implements _i32.ReactionRemoteDataSource {
  MockReactionRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i7.ReactionResponseModel> react({
    required _i31.ReactionTargetType? targetType,
    required String? targetId,
    required _i31.ReactionType? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#react, [], {
              #targetType: targetType,
              #targetId: targetId,
              #type: type,
            }),
            returnValue: _i11.Future<_i7.ReactionResponseModel>.value(
              _FakeReactionResponseModel_5(
                this,
                Invocation.method(#react, [], {
                  #targetType: targetType,
                  #targetId: targetId,
                  #type: type,
                }),
              ),
            ),
          )
          as _i11.Future<_i7.ReactionResponseModel>);

  @override
  _i11.Future<List<_i7.ReactionSummaryModel>> getReactionSummary({
    required _i31.ReactionTargetType? targetType,
    required String? targetId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getReactionSummary, [], {
              #targetType: targetType,
              #targetId: targetId,
            }),
            returnValue: _i11.Future<List<_i7.ReactionSummaryModel>>.value(
              <_i7.ReactionSummaryModel>[],
            ),
          )
          as _i11.Future<List<_i7.ReactionSummaryModel>>);

  @override
  _i11.Future<_i7.ReactionModel?> getUserReaction({
    required _i31.ReactionTargetType? targetType,
    required String? targetId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUserReaction, [], {
              #targetType: targetType,
              #targetId: targetId,
            }),
            returnValue: _i11.Future<_i7.ReactionModel?>.value(),
          )
          as _i11.Future<_i7.ReactionModel?>);
}

/// A class which mocks [FriendshipRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFriendshipRepository extends _i1.Mock
    implements _i33.FriendshipRepository {
  MockFriendshipRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i5.Either<_i9.Failure, _i34.FriendshipResponseEntity>>
  sendRequest({required String? toUserId}) =>
      (super.noSuchMethod(
            Invocation.method(#sendRequest, [], {#toUserId: toUserId}),
            returnValue:
                _i11.Future<
                  _i5.Either<_i9.Failure, _i34.FriendshipResponseEntity>
                >.value(
                  _FakeEither_3<_i9.Failure, _i34.FriendshipResponseEntity>(
                    this,
                    Invocation.method(#sendRequest, [], {#toUserId: toUserId}),
                  ),
                ),
          )
          as _i11.Future<
            _i5.Either<_i9.Failure, _i34.FriendshipResponseEntity>
          >);

  @override
  _i11.Future<_i5.Either<_i9.Failure, _i34.FriendshipResponseEntity>>
  acceptRequest({required String? requestId}) =>
      (super.noSuchMethod(
            Invocation.method(#acceptRequest, [], {#requestId: requestId}),
            returnValue:
                _i11.Future<
                  _i5.Either<_i9.Failure, _i34.FriendshipResponseEntity>
                >.value(
                  _FakeEither_3<_i9.Failure, _i34.FriendshipResponseEntity>(
                    this,
                    Invocation.method(#acceptRequest, [], {
                      #requestId: requestId,
                    }),
                  ),
                ),
          )
          as _i11.Future<
            _i5.Either<_i9.Failure, _i34.FriendshipResponseEntity>
          >);

  @override
  _i11.Future<_i5.Either<_i9.Failure, _i34.FriendshipResponseEntity>>
  rejectRequest({required String? requestId}) =>
      (super.noSuchMethod(
            Invocation.method(#rejectRequest, [], {#requestId: requestId}),
            returnValue:
                _i11.Future<
                  _i5.Either<_i9.Failure, _i34.FriendshipResponseEntity>
                >.value(
                  _FakeEither_3<_i9.Failure, _i34.FriendshipResponseEntity>(
                    this,
                    Invocation.method(#rejectRequest, [], {
                      #requestId: requestId,
                    }),
                  ),
                ),
          )
          as _i11.Future<
            _i5.Either<_i9.Failure, _i34.FriendshipResponseEntity>
          >);

  @override
  _i11.Future<_i5.Either<_i9.Failure, List<_i34.FriendRequestEntity>>>
  getPendingRequests() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingRequests, []),
            returnValue:
                _i11.Future<
                  _i5.Either<_i9.Failure, List<_i34.FriendRequestEntity>>
                >.value(
                  _FakeEither_3<_i9.Failure, List<_i34.FriendRequestEntity>>(
                    this,
                    Invocation.method(#getPendingRequests, []),
                  ),
                ),
          )
          as _i11.Future<
            _i5.Either<_i9.Failure, List<_i34.FriendRequestEntity>>
          >);

  @override
  _i11.Future<_i5.Either<_i9.Failure, List<_i34.FriendRequestEntity>>>
  getSentRequests() =>
      (super.noSuchMethod(
            Invocation.method(#getSentRequests, []),
            returnValue:
                _i11.Future<
                  _i5.Either<_i9.Failure, List<_i34.FriendRequestEntity>>
                >.value(
                  _FakeEither_3<_i9.Failure, List<_i34.FriendRequestEntity>>(
                    this,
                    Invocation.method(#getSentRequests, []),
                  ),
                ),
          )
          as _i11.Future<
            _i5.Either<_i9.Failure, List<_i34.FriendRequestEntity>>
          >);

  @override
  _i11.Future<_i5.Either<_i9.Failure, List<_i34.FriendEntity>>> getFriends() =>
      (super.noSuchMethod(
            Invocation.method(#getFriends, []),
            returnValue:
                _i11.Future<
                  _i5.Either<_i9.Failure, List<_i34.FriendEntity>>
                >.value(
                  _FakeEither_3<_i9.Failure, List<_i34.FriendEntity>>(
                    this,
                    Invocation.method(#getFriends, []),
                  ),
                ),
          )
          as _i11.Future<_i5.Either<_i9.Failure, List<_i34.FriendEntity>>>);

  @override
  _i11.Future<_i5.Either<_i9.Failure, List<_i34.FriendEntity>>> getUserFriends({
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUserFriends, [], {#userId: userId}),
            returnValue:
                _i11.Future<
                  _i5.Either<_i9.Failure, List<_i34.FriendEntity>>
                >.value(
                  _FakeEither_3<_i9.Failure, List<_i34.FriendEntity>>(
                    this,
                    Invocation.method(#getUserFriends, [], {#userId: userId}),
                  ),
                ),
          )
          as _i11.Future<_i5.Either<_i9.Failure, List<_i34.FriendEntity>>>);

  @override
  _i11.Future<_i5.Either<_i9.Failure, _i34.FriendshipStatusEntity>> isFriend({
    required String? userAId,
    required String? userBId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#isFriend, [], {
              #userAId: userAId,
              #userBId: userBId,
            }),
            returnValue:
                _i11.Future<
                  _i5.Either<_i9.Failure, _i34.FriendshipStatusEntity>
                >.value(
                  _FakeEither_3<_i9.Failure, _i34.FriendshipStatusEntity>(
                    this,
                    Invocation.method(#isFriend, [], {
                      #userAId: userAId,
                      #userBId: userBId,
                    }),
                  ),
                ),
          )
          as _i11.Future<_i5.Either<_i9.Failure, _i34.FriendshipStatusEntity>>);

  @override
  _i11.Future<_i5.Either<_i9.Failure, List<String>>> getFriendIds() =>
      (super.noSuchMethod(
            Invocation.method(#getFriendIds, []),
            returnValue:
                _i11.Future<_i5.Either<_i9.Failure, List<String>>>.value(
                  _FakeEither_3<_i9.Failure, List<String>>(
                    this,
                    Invocation.method(#getFriendIds, []),
                  ),
                ),
          )
          as _i11.Future<_i5.Either<_i9.Failure, List<String>>>);
}

/// A class which mocks [FriendshipRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFriendshipRemoteDataSource extends _i1.Mock
    implements _i35.FriendshipRemoteDataSource {
  MockFriendshipRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i8.FriendshipResponseModel> sendRequest({
    required String? toUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendRequest, [], {#toUserId: toUserId}),
            returnValue: _i11.Future<_i8.FriendshipResponseModel>.value(
              _FakeFriendshipResponseModel_6(
                this,
                Invocation.method(#sendRequest, [], {#toUserId: toUserId}),
              ),
            ),
          )
          as _i11.Future<_i8.FriendshipResponseModel>);

  @override
  _i11.Future<_i8.FriendshipResponseModel> acceptRequest({
    required String? requestId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#acceptRequest, [], {#requestId: requestId}),
            returnValue: _i11.Future<_i8.FriendshipResponseModel>.value(
              _FakeFriendshipResponseModel_6(
                this,
                Invocation.method(#acceptRequest, [], {#requestId: requestId}),
              ),
            ),
          )
          as _i11.Future<_i8.FriendshipResponseModel>);

  @override
  _i11.Future<_i8.FriendshipResponseModel> rejectRequest({
    required String? requestId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rejectRequest, [], {#requestId: requestId}),
            returnValue: _i11.Future<_i8.FriendshipResponseModel>.value(
              _FakeFriendshipResponseModel_6(
                this,
                Invocation.method(#rejectRequest, [], {#requestId: requestId}),
              ),
            ),
          )
          as _i11.Future<_i8.FriendshipResponseModel>);

  @override
  _i11.Future<List<_i8.FriendRequestModel>> getPendingRequests() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingRequests, []),
            returnValue: _i11.Future<List<_i8.FriendRequestModel>>.value(
              <_i8.FriendRequestModel>[],
            ),
          )
          as _i11.Future<List<_i8.FriendRequestModel>>);

  @override
  _i11.Future<List<_i8.FriendRequestModel>> getSentRequests() =>
      (super.noSuchMethod(
            Invocation.method(#getSentRequests, []),
            returnValue: _i11.Future<List<_i8.FriendRequestModel>>.value(
              <_i8.FriendRequestModel>[],
            ),
          )
          as _i11.Future<List<_i8.FriendRequestModel>>);

  @override
  _i11.Future<List<_i8.FriendModel>> getFriends() =>
      (super.noSuchMethod(
            Invocation.method(#getFriends, []),
            returnValue: _i11.Future<List<_i8.FriendModel>>.value(
              <_i8.FriendModel>[],
            ),
          )
          as _i11.Future<List<_i8.FriendModel>>);

  @override
  _i11.Future<List<_i8.FriendModel>> getUserFriends({
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUserFriends, [], {#userId: userId}),
            returnValue: _i11.Future<List<_i8.FriendModel>>.value(
              <_i8.FriendModel>[],
            ),
          )
          as _i11.Future<List<_i8.FriendModel>>);

  @override
  _i11.Future<_i8.FriendshipStatusModel> isFriend({
    required String? userAId,
    required String? userBId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#isFriend, [], {
              #userAId: userAId,
              #userBId: userBId,
            }),
            returnValue: _i11.Future<_i8.FriendshipStatusModel>.value(
              _FakeFriendshipStatusModel_7(
                this,
                Invocation.method(#isFriend, [], {
                  #userAId: userAId,
                  #userBId: userBId,
                }),
              ),
            ),
          )
          as _i11.Future<_i8.FriendshipStatusModel>);

  @override
  _i11.Future<List<String>> getFriendIds() =>
      (super.noSuchMethod(
            Invocation.method(#getFriendIds, []),
            returnValue: _i11.Future<List<String>>.value(<String>[]),
          )
          as _i11.Future<List<String>>);
}
